#!/bin/bash
# FitTrack MVP — Full Deploy Script
# Run from the project root: ./infrastructure/deploy_commands.sh

set -e  # Exit on error

echo "========================================"
echo "  FitTrack MVP — AWS Backend Deploy"
echo "========================================"

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# ── Check Prerequisites ──────────────────────────────────
echo ""
echo -e "${YELLOW}[1/6] Checking prerequisites...${NC}"

if ! command -v aws &> /dev/null; then
    echo -e "${RED}ERROR: AWS CLI not found. Install it with: pip install awscli${NC}"
    exit 1
fi

if ! command -v serverless &> /dev/null; then
    echo -e "${RED}ERROR: Serverless not found. Install it with: npm install -g serverless${NC}"
    exit 1
fi

if ! command -v node &> /dev/null; then
    echo -e "${RED}ERROR: Node.js not found. Install from https://nodejs.org${NC}"
    exit 1
fi

if ! command -v python3 &> /dev/null; then
    echo -e "${RED}ERROR: Python 3 not found${NC}"
    exit 1
fi

echo -e "${GREEN}✓ All prerequisites found${NC}"

# ── AWS Identity Check ───────────────────────────────────
echo ""
echo -e "${YELLOW}[2/6] Verifying AWS credentials...${NC}"
AWS_IDENTITY=$(aws sts get-caller-identity 2>&1)
if [ $? -ne 0 ]; then
    echo -e "${RED}ERROR: AWS credentials not configured. Run: aws configure${NC}"
    exit 1
fi
echo -e "${GREEN}✓ AWS credentials valid${NC}"
echo "$AWS_IDENTITY"

# ── Install Dependencies ─────────────────────────────────
echo ""
echo -e "${YELLOW}[3/6] Installing Node.js dependencies...${NC}"
cd "$(dirname "$0")/../backend"

if [ ! -f "package.json" ]; then
    npm init -y
fi

npm install --save-dev serverless-python-requirements 2>/dev/null || true
echo -e "${GREEN}✓ Node.js dependencies installed${NC}"

# ── Install Python Dependencies ──────────────────────────
echo ""
echo -e "${YELLOW}[4/6] Installing Python dependencies...${NC}"
pip3 install -r requirements.txt --break-system-packages 2>/dev/null || \
pip3 install -r requirements.txt 2>/dev/null || \
pip install -r requirements.txt
echo -e "${GREEN}✓ Python dependencies installed${NC}"

# ── Deploy ────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}[5/6] Deploying to AWS (this takes 3-5 minutes)...${NC}"
STAGE=${1:-dev}
REGION=${2:-us-east-1}

serverless deploy --stage $STAGE --region $REGION --verbose

# ── Extract Outputs ───────────────────────────────────────
echo ""
echo -e "${YELLOW}[6/6] Extracting deployment outputs...${NC}"

STACK_NAME="fitness-tracker-mvp-$STAGE"
API_URL=$(aws cloudformation describe-stacks \
    --stack-name $STACK_NAME \
    --query 'Stacks[0].Outputs[?OutputKey==`ApiGatewayUrl`].OutputValue' \
    --output text 2>/dev/null || echo "Check AWS Console for API URL")

USER_POOL_ID=$(aws cloudformation describe-stacks \
    --stack-name $STACK_NAME \
    --query 'Stacks[0].Outputs[?OutputKey==`UserPoolId`].OutputValue' \
    --output text 2>/dev/null || echo "Check AWS Console for User Pool ID")

USER_POOL_CLIENT_ID=$(aws cloudformation describe-stacks \
    --stack-name $STACK_NAME \
    --query 'Stacks[0].Outputs[?OutputKey==`UserPoolClientId`].OutputValue' \
    --output text 2>/dev/null || echo "Check AWS Console for Client ID")

echo ""
echo "========================================"
echo -e "${GREEN}  ✓ DEPLOY COMPLETE!${NC}"
echo "========================================"
echo ""
echo "📌 UPDATE THESE VALUES IN YOUR FLUTTER APP:"
echo ""
echo "   File: mobile_app/lib/main.dart"
echo "   const String cognitoUserPoolId = '$USER_POOL_ID';"
echo "   const String cognitoAppClientId = '$USER_POOL_CLIENT_ID';"
echo ""
echo "   File: mobile_app/lib/services/api_service.dart"
echo "   const String _baseUrl = '$API_URL';"
echo ""
echo "========================================"
echo ""

# Write config to file for reference
cat > ../mobile_app/aws_config.txt << EOF
# AWS Configuration — Generated by deploy_commands.sh
# Update these values in your Flutter app

API_GATEWAY_URL=$API_URL
COGNITO_USER_POOL_ID=$USER_POOL_ID
COGNITO_APP_CLIENT_ID=$USER_POOL_CLIENT_ID
STAGE=$STAGE
REGION=$REGION
EOF

echo -e "${GREEN}✓ Config saved to mobile_app/aws_config.txt${NC}"
echo ""
echo "Next step: Update mobile_app/lib/main.dart and mobile_app/lib/services/api_service.dart"
echo "Then run: cd mobile_app && flutter pub get && flutter run"
